export const trios = [
  { round: '😤 Impossible Choice', characters: ['Zero Two', 'Yor Forger', 'Makima'] },
  { round: '😤 Impossible Choice', characters: ['Hinata Hyuga', 'Sakura Haruno', 'Tsunade'] },
  { round: '😤 Impossible Choice', characters: ['Nami', 'Nico Robin', 'Boa Hancock'] },
  { round: '😤 Impossible Choice', characters: ['Rem', 'Ram', 'Emilia'] },
  { round: '💀 Waifu Wars',        characters: ['Nezuko Kamado', 'Nobara Kugisaki', 'Maki Zenin'] },
  { round: '💀 Waifu Wars',        characters: ['Mikasa Ackerman', 'Historia Reiss', 'Sasha Braus'] },
  { round: '💀 Powerhouse Trio',   characters: ['Albedo', 'Shalltear', 'Satoru Gojo'] },
  { round: '🔥 Villain Edition',   characters: ['Makima', 'Toga Himiko', 'Esdeath'] },
  { round: '😭 Betrayal Round',    characters: ['Sakura Haruno', 'Orihime Inoue', 'Serena'] },
  { round: '🤯 Crossover Chaos',   characters: ['Yor Forger', 'Nobara Kugisaki', 'Zero Two'] },
];

export const chars = {
  'Zero Two':         { img: 'images/zero-two.jpg',     anime: 'Darling in the Franxx' },
  'Yor Forger':       { img: 'images/yor.jpg',          anime: 'Spy x Family' },
  'Makima':           { img: 'images/makima.jpg',       anime: 'Chainsaw Man' },
  'Hinata Hyuga':     { img: 'images/hinata.jpg',       anime: 'Naruto' },
  'Sakura Haruno':    { img: 'images/sakura.jpg',       anime: 'Naruto' },
  'Tsunade':          { img: 'images/tsunade.jpg',     anime: 'Naruto' },
  'Nami':             { img: 'images/nami.jpg',         anime: 'One Piece' },
  'Nico Robin':       { img: 'images/nico-robin.png',   anime: 'One Piece' },
  'Boa Hancock':      { img: 'images/boa-hancock.jpg',  anime: 'One Piece' },
  'Rem':              { img: 'images/rem.jpg',          anime: 'Re:Zero' },
  'Ram':              { img: 'images/ram.jpg',          anime: 'Re:Zero' },
  'Emilia':           { img: 'images/emilia.jpg',       anime: 'Re:Zero' },
  'Nezuko Kamado':    { img: 'images/nezuko.jpeg',      anime: 'Demon Slayer' },
  'Nobara Kugisaki':  { img: 'images/nobara.png',       anime: 'Jujutsu Kaisen' },
  'Maki Zenin':       { img: 'images/maki-zenin.jpeg',  anime: 'Jujutsu Kaisen' },
  'Mikasa Ackerman':  { img: 'images/mikasa.jpg',       anime: 'Attack on Titan' },
  'Historia Reiss':   { img: 'images/historia.jpg',     anime: 'Attack on Titan' },
  'Sasha Braus':      { img: 'images/sasha.jpg',        anime: 'Attack on Titan' },
  'Albedo':           { img: 'images/albedo.jpg',       anime: 'Overlord' },
  'Shalltear':        { img: 'images/shalltear.jpeg',   anime: 'Overlord' },
  'Satoru Gojo':      { img: 'images/gojo.webp',        anime: 'Jujutsu Kaisen' },
  'Toga Himiko':      { img: 'images/toga.jpg',         anime: 'My Hero Academia' },
  'Esdeath':          { img: 'images/esdeath.jpg',      anime: 'Akame ga Kill' },
  'Orihime Inoue':    { img: 'images/orihime.jpg',      anime: 'Bleach' },
  'Serena':           { img: 'images/serena.jpg',       anime: 'Pokémon' },
};
